### ISSUE TITLE
[Document] broken link in magit.vc

### ISSUE THREAD

**Issue by conao3** [magit/ghub#100]
Hi! I found broken link in magit.vc

(auth)Top in [2.4 how Ghub uses Auth-Source](https://magit.vc/manual/ghub/How-Ghub-uses-Auth_002dSource.html#How-Ghub-uses-Auth_002dSource) links https://magit.vc/manual/auth/index.html#Top but https://www.gnu.org/software/emacs/manual/html_mono/auth.html is better?

I checked the source to fix it, but the source is correct as an Org source, but HTML seems wrong. Therefore, I will only report.

---
P.S.
Do you maintain magit.vc? If you don't maintain it, close this issue.

**Comment by tarsius** [comment]
That's because magit.vc does not host a copy of the `auth-source` manual. It is possible to tell...something...where the "other" manuals are. I have done that for the Emacs manuals--that is why https://magit.vc/manual/magit/Installing-from-Melpa.html knows that "(emacs)Packages" is located at https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html#Packages. Unfortunately I cannot remember or uncover how I have done that in the past. Whatever it is, I probably did it inside one of the repositories https://github.com/magit/magit or https://github.com/magit/magit.vc, but grepping for reasonable strings didn't reveal anything.

**Comment by conao3** [comment]
OK, thanks! I will continue to investigate.

**Comment by tarsius** [comment]
Fixed. Here's how it works: https://www.gnu.org/software/texinfo/manual/texinfo/html_node/HTML-Xref-Configuration.html.

**Comment by conao3** [comment]
Good, thanks!
