### ISSUE TITLE
Allow local username configuration

### ISSUE THREAD

**Issue by jtrakk** [magit/ghub#103]
I would like to use `git config --local github.user` instead of `--global` to support multiple accounts without worrying about accidentally picking the wrong one for each repository. Could there be a configuration variable for allowing this? I believe it would only be checked in `(ghub--username)`.

**Comment by vermiculus** [comment]
I.e., when setting the username? A better interface might be some keybinding in the minibuffer to switch between `--local` and `--global` (a la transient, but far more basic) rather than exposing some sort of defcustom.

    Git variable `%s' is unset.  Globally (C-t) set to:
    *presses C-t*
    Git variable `%s' is unset.  Locally (C-t) set to:

I'm horrible at these things, but you get the idea. There's probably somewhere else in Magit that can give us precedence for a pattern.

**Comment by tarsius** [comment]
The idea is that most users only need one identity and that users with other needs should perform the necessary configuration manually. But your argument that you don't want to risk falling back to the potentially inappropriate global value makes sense.

Of course forcing all users to make a choice has a cost too: users might might select "locally" when really they should have selected "globally".
