### ISSUE TITLE
error in process filter: BUG: missing headers

### ISSUE THREAD

**Issue by otavioschwanck** [magit/ghub#120]
On a large projet that i have, (with 1758 pull requests), more then 40 open pull requests), when fetching page 14, i get:

```
error in process filter: ghub--handle-response-headers: BUG: missing headers
  See https://github.com/magit/ghub/issues/81.
  url: https://api.github.com/graphql
  headers: 0
  status: nil
  buffer: #<buffer  *http api.github.com:443*>

```

On a small project, all works fine.

Magit 2fb3bf7, Git 2.27.0, Emacs 27.1, gnu/linux

OS: Ubuntu 20.10

I also tried with (setq ghub-use-workaround-for-emacs-bug t) and didn't work.

**Comment by tarsius** [comment]
> On a large projet that i have

Can you share what project that is?

**Comment by otavioschwanck** [comment]
> > On a large projet that i have
> 
> Can you share what project that is?

Is a business project, is from the company that i work.

The info that that i can share is:

Now has 25 open pull requests
1733 closed pulll requests

**Comment by otavioschwanck** [comment]
@tarsius for some unkown reason, today tried and worked.  I don't changed nothing.  You can close the issue if you want,

**Comment by tarsius** [comment]
> for some unkown reason, today tried and worked. I don't changed nothing. You can close the issue if you want,

My next suggestion was going to be "wait a day or two and try again". To problem is that very seldomly the `url` package somehow completely loses the response, probably because the server responded in some surprising but (we can only assume) valid way. Having no data beyond "it happened again" makes it very hard to debug this, but luckily it always gets fixed by waiting a day or two. :roll_eyes:
