### ISSUE TITLE
Consider dropping Emacs 25 requirement

### ISSUE THREAD

**Issue by Fuco1** [magit/ghub#17]
Hi.  Would it be possible to downgrade the Emacs 25 requirement to Emacs 24?  I don't know what features of E25 exactly are being used here but maybe they could be backported? Or a separate branch could be set up without this requirement.

Personally I feel it is a bit too early dropping Emacs 24 support (and this also affects me as I still use it in some environments).

If you point me to where the problem is I could maybe provide a patch myself.

**Comment by tarsius** [comment]
I think `subr-x` did not exist before 25 and that there have some big changes in 25's `auth-source`. 

Generally I tend to require 25 for all of my smaller packages right from the start, because that way I won't later have to justify why I *stop* supporting 24. Also it allows me to not worry about accidentally breaking compatibility.  For packages that I don't expect to get popular for a long time (or ever) I am even more inclined to just claim that at least 25 is required - in some cases that might not even be true.

`ghub` got somewhat popular before I expected that to happen. I mean I am not even done adding decent error handling... Originally it was only intended to be used by the tools used to maintain the Emacsmirror. So now that it has users and at least one of them wants to use 24, I might be willing to accept a compatibility patch, but I have to see it first.

**Comment by Fuco1** [comment]
All right, I'll see if I will have some time to go over this.  Please don't spend your time, you have better projects to handle :)

Thanks for confirming you would be up for it to take the patch.

**Comment by tarsius** [comment]
This kinda took care of itself. Except for one `pcase-lambda` all the stuff that needed Emacs 25 has disappeared for other reasons.
