### ISSUE TITLE
Using the wizard (via magithub) for auth token fails with HTTP 400 Bad Request

### ISSUE THREAD

**Issue by Tebro** [magit/ghub#62]
After filling in username and password the wizard dies with a message saying that the response received was 400 Bad Request and that github did not return JSON.

**Comment by tarsius** [comment]
> the response received was 400 Bad Request and that github did not return JSON.

When that happens then Github returned a html document, which always (regardless of what actually happened) contains the same error message. I don't remember what it was, but I think it is something to the effect of "something went wrong on the server and we will fix it".

I have seen such errors a few times during development and in some of these cases it was because the request itself was invalid, i.e. not because something went wrong on the server. At other times however the request was perfectly valid so something must indeed have gone wrong on the server. However because the error message sometimes is correct and sometimes is wrong, it is of no use, which is why `ghub` simply returns the error you mentioned.

That of course makes it rather difficult to figure out what actually happened when someone opens such an issue...

Because things sometimes do go wrong on Github's side and because many other users have successfully created a token, I am going to assume that Github was having difficulties when you made the request and that it would succeed if you tried again now. So I am closing this, but if it still doesn't work, then please ask me to reopen this. In that case you will have to provide a lot more information though, because otherwise all we know is that something went wrong and apparently its not Github's fault.
