### ISSUE TITLE
Accessing bitbucket private repos

### ISSUE THREAD

**Issue by pdixon** [magit/ghub#70]
In the manual you said you were unable to access any private repos. It seems to be working for me.

 If I call
``` elisp
(buck-get "repositories/" '((role . "contributor") (q . "scm=\"git\"")) :unpaginate t :auth 'basic)
```
and give an app password when prompted I get back all the git repos I have write access to including private repos.

Bitbucket's documentation for the `repositories` says it returns public repos. However the documentation of the response for the endpoint does include the `is_private` field.

The `users/{username}/repositories` endpoint is documented to return private repos, but it doesn't for me, at least not with the app password I created.

**Comment by tarsius** [comment]
> The `users/{username}/repositories` endpoint is documented to return private repos, but it doesn't for me, at least not with the app password I created.

That's the only thing I tried and what I want to use because I can use something equivalent with all the other forges.

But I don't want to shoot the messenger. :smiley: Thanks for letting me know.

> If I call
> ``` elisp
> (buck-get "repositories/" '((role . "contributor") (q . "scm=\"git\"")) :unpaginate t :auth 'basic)
> ```
> and give an app password when prompted I get back all the git repos I have write access to including > private repos.

However

``` elisp
(buck-get "repositories/" '((role . "contributor") (q . "scm=\"git\"")) :unpaginate t)
```

does not work. It does not even return public repositories. I cannot see any legitimate reason for why this should only work when using basic authentication but not when using a token, so that just reinforces my impression that the whole thing is buggy and you have to get lucky for the thing you want to do to actually work.

So it looks like with enough trial and error and then jumping through some hoops one can get useful information out of the bitbucket api, but I am yet to implement basic support for three other, well behaved, forge apis in the new `forge` package, so I will safe the pain of dealing with bitbucket for a future that may or may not ever come. :stuck_out_tongue_winking_eye:
