### ISSUE TITLE
HTTP Error: 502, "Bad gateway", "/graphql"

### ISSUE THREAD

**Issue by nicklan** [magit/ghub#83]
I'm still getting an error similar to #20 on a fairly large repo (running `20190107.1955`).  I can pull notifications, and that works okay, but trying to do `F-y` results in:
```
Pulling REPO...
error in process filter: ghub--signal-error: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CC2C:4FEA:A1771C1:CBF40CE:5C33F7E5` when reporting this issue."))))
error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data . "null") (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `CC2C:4FEA:A1771C1:CBF40CE:5C33F7E5` when reporting this issue."))))
```

Unlike above however, even if I restart the magit buffer there are no pull requests or issues listed.
Let me know if there's more debug info that could help.

Thanks!

**Comment by tarsius** [comment]
My best idea on how to deal with this is to just automatically to try again a few times.

The problem is on the Github's side.

This is what the error means.

> 502 Bad Gateway
>   The server was acting as a gateway or proxy and received an invalid response from the upstream server.

Github provides some additional information in the response:

> Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug.

My guess is that it is a timeout due to temporary overload. I have seen this error myself before, but when I did then simply trying again always worked.
And then:

> Please include `BD08:0667:1E6E491:408B28D:5C45D699` when reporting this issue.

Could you please collect a few such error ids and then send an email to Github asking them what has gone wrong for them.

But I fear that will not lead anywhere. Expected response "we give requests n time units to succeed and if it takes longer then we send a 502".

There actually was one situation where we could reproduce this issue more consistently: fetching the topics associated with the notifications that were fetched earlier. We solved that by fetching at most 100 topics at a time.

So if you run into this problem, then determine whether it happens when fetching notifications or when fetching other things. If it is the former then fetching fewer topics-for-notifications at a time might help.

**Comment by matthew-piziak** [comment]
Can reproduce on `nixpkgs`. Shame that GitHub is apparently just getting outscaled here. The repository has ~3200 issues at the moment.

**Comment by seanfarley** [comment]
I can also get this consistently on the [xonsh](github.com/xonsh/xonsh) repo. Fetching notifications works but `forge-pull` always fails. Is there a workaround?

**Comment by tarsius** [comment]
> Is there a workaround?

The workaround seems to be: try again ten seconds later. For our purpose this isn't actually a large repository. It's smaller than the magit repository for example, which never caused my any troubles.

But I wasn't able to fetch the data for this repository on the first try either. It failed pretty early on and my guess is that it took to long to wake something up. On the second try that thing was already awake.

**Comment by seanfarley** [comment]
I see; thanks very much for the explanation! Upon trying that repo again, you were right, it did work.

**Comment by matthuszagh** [comment]
Just to add to the conversation I'm also experiencing this with Nixpkgs.

**Comment by tarsius** [comment]
This doesn't happen very often and when it does, then it isn't our fault. While we could investigate whether it might possibly be an good idea to simply retry when this error occurs I don't think it would be worth the effort.

**Comment by matthuszagh** [comment]
Naive question, but is there any way to perform `forge-pull` incrementally for large repos? Every time I try with Nixpkgs it fails at a different point but seems to start over from scratch. I've had no issues with smaller repos, but I've tried a bunch of times with Nixpkgs and it seems unlikely it'll be able to make it through the whole thing within one attempt.

**Comment by tarsius** [comment]
That's huuuuuuge. No, an "incremental initial pull" is not supported. If you were to succeed downloading everything, then you would just have another issue: forge would be way to slow in every day use.

Of course theoretically it would possible to address all that, but I am not enough people, so forge will likely never be improved to support such humongous repositories. Sorry.

**Comment by matthuszagh** [comment]
No worries. Thanks for the response anyway!

**Comment by yashi** [comment]
This happened to me with https://github.com/zephyrproject-rtos/zephyr.  And I did retried 10 times and voila it finally worked!

**Comment by mkleehammer** [comment]
In case it is helpful to someone, I got this error when fetching all topics.  I had set up Forge a few months in the past but didn't really use it so I was picking it up again.

When I tried to fetch one topic, it told me it couldn't until I added the repo.  I did so and as part of that it fetched all items without any problems.
