### ISSUE TITLE
502 Bad Gateway on Gitlab

### ISSUE THREAD

**Issue by cpitclaudel** [magit/ghub#87]
Hi there,

Thanks for the hard work! There's an ongoing discussion on emacs-devel about switching Emacs from debbugs to gitlab, and one key question is how contributors would interact with but reports without leaving Emacs.

Of course, forge is the leading candidate for this interaction. But there is worry about how large a repo forge (or, more precisely, the protocols that forge uses to talk to gitlab) can handle.

The concrete issue I'm running into is the following: when I try to fetch forge topics for the gitlab-ce repository at https://gitlab.com/gitlab-org/gitlab-ce.git, I get the following message:

```
error in process filter: HTTP Error: 502, "Bad gateway", "/api/v4/projects/gitlab-org%2Fgitlab-ce/forks?id=gitlab-org%2Fgitlab-ce&membership=false&order_by=created_at&owned=false&page=14&per_page=100&repository_checksum_failed=false&simple=true&sort=desc&starred=false&wiki_checksum_failed=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false", ((message . "GitLab is not responding") (documentation_url . "https://github.com/magit/ghub/wiki/Github-Errors"))
```

It seems to be a Gitlab issue, but when I manually browse to that URL I get seemingly-proper results. Is there a ticket open about this in the Gitlab tracker? (I couldn't find one.) Or is it a problem with the way forge uses the API?

More importantly, do you have a sense of how many topics forge can fetch from a Gitlab repo without trouble? If Emacs' debbugs has fewer bugs than that, this whole issue wouldn't be a worry.

Thanks again!

**Comment by To1ne** [comment]
I'm curious to know if having decent GraphQL support on GitLab would help? If so, I'd like to push forward the effort to get that in GitLab.

**Comment by tarsius** [comment]
@To1ne I don't think it would help with this issue, but it would help a lot anyway.

Regarding this issue:

> 502 Bad Gateway
>   The server was acting as a gateway or proxy and received an invalid response from the upstream server.

My guess is that it is a timeout due to temporary overload. Simply retrying usually "fixed" it for me. So teaching `ghub` to simply retry when this error occurs will probably fix this issue in most cases.

----

Regarding GraphQL:

GraphQL isn't at all designed for what `forge` is doing, quite the opposite. Despite that it works better than REST.

Forge wants to fetch "all" data. What would be best is if at least the basic data were tracked using Git in addition to being stored in a database that has to be accessed using REST or GraphQL. The refs used for this could be "read-only", i.e. it would not be possible to reply on an issue by adding the appropriate file and pushing. But it would be very nice if all the topics could be fetched using just Git. I think that would lead to a proliferation of tools similar to `forge`. It certainly would make things much easier on the (non-web) client side.

But lacking that, GraphQL is also a big step forward. What is causing issues for Forge is that pagination is a core concept. At least in practice you cannot say "Look, I am going to keep making requests until you have coughed up all the data, so you might as well give me all of it right now". The result was that I had to write complicated code that does automatic unpagination. There is at least one unresolved issue related to this: #86.

Fetching the needed data from Github using GraphQL is *much* faster than fetching it from Gitlab using REST. I don't remember exactly but I think that what would take ten minutes for Github would take hours for Gitlab. I have been recently been made aware that `forge` came up on emacs-devel and was asked whether `forge` could handle such a large project. At this time it is not. With GraphQL it would become feasible at least, but the initial fetch might still take hours anyway.

I would like Forge to be usable for projects like Emacs itself but it is still early days and a lot has to be done before that is really feasible.

Regardless of what you do (and I would very much welcome GraphQL support) I think ghub/forge has to learn to do sparse clones, just like git did.

**Comment by tarsius** [comment]
@cpitclaudel I was planning to fly under the radar until Forge has majored before bringing it up on emacs-devel. There is still a lot to be done before using it for Emacs becomes feasible. But from the sound of it is also going to take a long time before Emacs switches to Gitlab, if ever. So I got some time too. ;-)

I will try to write more soonish, but right now I am in "finishing stuff" mode and this is a whole new can of worms.

**Comment by cpitclaudel** [comment]
Thanks for your efforts. No pressure. Your work is just that good :), so of course it spreads quickly ^^

**Comment by tarsius** [comment]
This doesn't happen very often and when it does, then it isn't our fault. While we could investigate whether it might possibly be an good idea to simply retry when this error occurs I don't think it would be worth the effort.
